language: php

sudo: false

php:
  - 5.6

env:
  - SYMFONY_VERSION=2.6.*
  - SYMFONY_VERSION="dev-master symfony/debug:~2.7@dev symfony/http-kernel:~2.7@dev"

before_script:
  - composer self-update
  - composer require symfony/framework-bundle:${SYMFONY_VERSION} --no-update
  - composer update --no-interaction --prefer-source
  - echo "always_populate_raw_post_data = -1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - ./src/BeSimple/SoapClient/Tests/bin/phpwebserver.sh
  - ./src/BeSimple/SoapClient/Tests/bin/axis.sh

script:
  - phpunit --coverage-text

matrix:
  allow_failures:
    - env: SYMFONY_VERSION="dev-master symfony/debug:~2.7@dev symfony/http-kernel:~2.7@dev"
