language: php

sudo: required

php:
  - 5.6

env:
  - SYMFONY_VERSION=2.6.*
  - SYMFONY_VERSION="dev-master symfony/debug:~2.7@dev symfony/http-kernel:~2.7@dev"

before_script:
  - sudo composer self-update
  - ./src/BeSimple/SoapClient/Tests/bin/phpwebserver.sh
  - ./src/BeSimple/SoapClient/Tests/bin/axis.sh

script:
  - phpunit --coverage-text

matrix:
  allow_failures:
    - env: SYMFONY_VERSION="dev-master symfony/debug:~2.7@dev symfony/http-kernel:~2.7@dev"
